//
//  FrenchAutocorrectService.swift
//  SwiftSpeak
//
//  French language autocorrection service
//  Handles accent restoration, contractions, proper nouns, and common corrections
//
//  SHARED: This file is used by both SwiftSpeak and SwiftSpeakKeyboard targets
//

import Foundation

/// French autocorrection service for intelligent French text correction
enum FrenchAutocorrectService {

    // MARK: - Main Correction Method

    /// Fix French word - restores accents, fixes contractions, and applies corrections
    /// Returns nil if no correction needed
    static func fixFrenchWord(_ word: String) -> String? {
        let lowercased = word.lowercased()

        // Check for contraction fixes (highest priority - structural errors)
        if let corrected = frenchContractions[lowercased] {
            return preserveCase(original: word, corrected: corrected)
        }

        // Check for accent restorations (most common need)
        if let corrected = frenchAccents[lowercased] {
            return preserveCase(original: word, corrected: corrected)
        }

        // Check for common misspellings
        if let corrected = frenchMisspellings[lowercased] {
            return preserveCase(original: word, corrected: corrected)
        }

        // Check for proper nouns (cities, countries, etc.)
        if let properNoun = frenchProperNouns[lowercased] {
            return properNoun
        }

        return nil
    }

    /// Check if word should be capitalized (French proper nouns)
    static func shouldCapitalizeFrench(_ word: String) -> String? {
        let lowercased = word.lowercased()
        return frenchProperNouns[lowercased]
    }

    // MARK: - Helper Methods

    /// Preserve the original case pattern when applying correction
    private static func preserveCase(original: String, corrected: String) -> String {
        guard !original.isEmpty, !corrected.isEmpty else { return corrected }

        let isAllCaps = original == original.uppercased() && original.count > 1
        let isCapitalized = original.first?.isUppercase ?? false

        if isAllCaps {
            return corrected.uppercased()
        } else if isCapitalized {
            return corrected.prefix(1).uppercased() + corrected.dropFirst()
        }
        return corrected
    }

    // MARK: - French Contractions Dictionary
    // Missing apostrophes in common French contractions

    private static let frenchContractions: [String: String] = [
        // ==========================================
        // ESSENTIAL CONTRACTIONS (very high frequency)
        // ==========================================

        // c'est - "it is" (most common)
        "cest": "c'est",
        "cetait": "c'était",

        // j'ai, j'aime, etc. - "I have", "I like"
        "jai": "j'ai",
        "jaime": "j'aime",
        "jattends": "j'attends",
        "jarrive": "j'arrive",
        "jessaie": "j'essaie",
        "jessaye": "j'essaye",
        "jespere": "j'espère",
        "jhabite": "j'habite",
        "jirai": "j'irai",
        "joublie": "j'oublie",
        "jy": "j'y",
        "jen": "j'en",
        "jentends": "j'entends",
        "jecris": "j'écris",
        "jecoute": "j'écoute",
        "jignore": "j'ignore",
        "jimagine": "j'imagine",
        "jinsiste": "j'insiste",
        "jinvite": "j'invite",

        // l'homme, l'eau, etc. - definite article elision
        "lhomme": "l'homme",
        "leau": "l'eau",
        "lair": "l'air",
        "lamour": "l'amour",
        "lannee": "l'année",
        "largent": "l'argent",
        "lart": "l'art",
        "laventure": "l'aventure",
        "lami": "l'ami",
        "lamie": "l'amie",
        "lavis": "l'avis",
        "lecole": "l'école",
        "leglise": "l'église",
        "lenfant": "l'enfant",
        "letat": "l'état",
        "letude": "l'étude",
        "leurope": "l'Europe",
        "lexemple": "l'exemple",
        "lexperience": "l'expérience",
        "lhistoire": "l'histoire",
        "lhiver": "l'hiver",
        "lhonneur": "l'honneur",
        "lhopital": "l'hôpital",
        "lhotel": "l'hôtel",
        "lheure": "l'heure",
        "lidee": "l'idée",
        "limage": "l'image",
        "limportance": "l'importance",
        "linformation": "l'information",
        "linteret": "l'intérêt",
        "loeil": "l'oeil",
        "loeuvre": "l'oeuvre",
        "loffre": "l'offre",
        "lopinion": "l'opinion",
        "lordre": "l'ordre",
        "lun": "l'un",
        "lune": "l'une",
        "luniversite": "l'université",
        "lusage": "l'usage",
        "lentreprise": "l'entreprise",
        "levenement": "l'événement",
        "laction": "l'action",
        "laccident": "l'accident",
        "laccord": "l'accord",
        "lactivite": "l'activité",
        "ladresse": "l'adresse",
        "laffaire": "l'affaire",
        "lage": "l'âge",
        "laide": "l'aide",
        "lalcool": "l'alcool",
        "lalliance": "l'alliance",
        "lambiance": "l'ambiance",
        "lanalyse": "l'analyse",
        "lange": "l'ange",
        "langoisse": "l'angoisse",
        "lanimal": "l'animal",
        "lannonce": "l'annonce",
        "lappartement": "l'appartement",
        "lappel": "l'appel",
        "lapplication": "l'application",
        "lapproche": "l'approche",
        "larbre": "l'arbre",
        "larchitecture": "l'architecture",
        "larriere": "l'arrière",
        "larticle": "l'article",
        "lartiste": "l'artiste",
        "laspect": "l'aspect",
        "lassociation": "l'association",
        "latmosphere": "l'atmosphère",
        "lattaque": "l'attaque",
        "lattention": "l'attention",
        "lattitude": "l'attitude",
        "lautorite": "l'autorité",
        "lautre": "l'autre",
        "lavance": "l'avance",
        "lavantage": "l'avantage",
        "lavenir": "l'avenir",
        "lavion": "l'avion",
        "lavocat": "l'avocat",

        // d'accord, d'abord, etc. - "of" elision
        "daccord": "d'accord",
        "dabord": "d'abord",
        "dailleurs": "d'ailleurs",
        "dapres": "d'après",
        "dautre": "d'autre",
        "dautres": "d'autres",
        "dici": "d'ici",
        "dun": "d'un",
        "dune": "d'une",
        "dou": "d'où",
        "dehors": "dehors",
        "dentre": "d'entre",
        "dessus": "dessus",
        "dessous": "dessous",

        // qu'il, qu'elle, qu'est-ce - "that" elision
        "quil": "qu'il",
        "quelle": "qu'elle",
        "quils": "qu'ils",
        "quelles": "qu'elles",
        "quon": "qu'on",
        "questce": "qu'est-ce",
        "quest": "qu'est",
        "quen": "qu'en",
        "quy": "qu'y",

        // n'est, n'a, etc. - negation elision
        "nest": "n'est",
        "na": "n'a",
        "nai": "n'ai",
        "navait": "n'avait",
        "navais": "n'avais",
        "netait": "n'était",
        "netais": "n'étais",
        "ny": "n'y",
        "nimporte": "n'importe",
        "nont": "n'ont",
        "naura": "n'aura",
        "naurait": "n'aurait",
        "naurais": "n'aurais",
        "nexiste": "n'existe",
        "noublie": "n'oublie",
        "noubliez": "n'oubliez",
        "nhesitez": "n'hésitez",

        // s'il, s'appelle, etc. - reflexive/conditional elision
        "sil": "s'il",
        "sils": "s'ils",
        "sappelle": "s'appelle",
        "sappellent": "s'appellent",
        "sarrete": "s'arrête",
        "sarretent": "s'arrêtent",
        "sen": "s'en",
        "sy": "s'y",
        "sagit": "s'agit",
        "sattend": "s'attend",
        "sattendent": "s'attendent",
        "souvre": "s'ouvre",
        "souvrent": "s'ouvrent",
        "soccupe": "s'occupe",
        "soccupent": "s'occupent",
        "sinstalle": "s'installe",
        "sinstallent": "s'installent",
        "sameliore": "s'améliore",

        // t'aime, t'appelle, etc. - second person elision
        "taime": "t'aime",
        "tappelle": "t'appelle",
        "tattends": "t'attends",
        "ten": "t'en",
        "ty": "t'y",
        "toccupes": "t'occupes",
        "tarretes": "t'arrêtes",
        "tinquiete": "t'inquiète",

        // m'a, m'appelle, etc. - first person object elision
        "mappelle": "m'appelle",
        "men": "m'en",
        "my": "m'y",
        "mattend": "m'attend",
        "moccupe": "m'occupe",
        "minteresse": "m'intéresse",
        "minquiete": "m'inquiète",
        "mexplique": "m'explique",
        "maide": "m'aide",

        // aujourd'hui - special compound
        "aujourdhui": "aujourd'hui",

        // presqu'île, quelqu'un, etc. - special elisions
        "presquile": "presqu'île",
        "quelquun": "quelqu'un",
        "quelquune": "quelqu'une",
        "quelquuns": "quelques-uns",
        "quelquunes": "quelques-unes",
        "jusqua": "jusqu'à",
        "jusquau": "jusqu'au",
        "jusquaux": "jusqu'aux",
        "jusquici": "jusqu'ici",
        "jusquou": "jusqu'où",
        "jusquen": "jusqu'en",
        "lorsquil": "lorsqu'il",
        "lorsquelle": "lorsqu'elle",
        "lorsquils": "lorsqu'ils",
        "lorsquelles": "lorsqu'elles",
        "lorsquon": "lorsqu'on",
        "puisquil": "puisqu'il",
        "puisquelle": "puisqu'elle",
        "puisquils": "puisqu'ils",
        "puisquelles": "puisqu'elles",
        "puisquon": "puisqu'on",
        "quoiquil": "quoiqu'il",
        "quoiquelle": "quoiqu'elle",
    ]

    // MARK: - French Accents Dictionary
    // Words typed without French accents → correct form with accents

    private static let frenchAccents: [String: String] = [
        // ==========================================
        // MOST COMMON WORDS (highest frequency)
        // ==========================================

        // être (to be) - most common verb
        "etre": "être",
        "ete": "été",
        "etais": "étais",
        "etait": "était",
        "etions": "étions",
        "etiez": "étiez",
        "etaient": "étaient",
        "etes": "êtes",
        "etant": "étant",

        // "à" preposition (at/to)
        "a": "à",

        // ça - demonstrative
        "ca": "ça",

        // Common words with é (acute accent)
        "ecole": "école",
        "ecoute": "écoute",
        "ecouter": "écouter",
        "economie": "économie",
        "economique": "économique",
        "ecrire": "écrire",
        "ecrit": "écrit",
        "ecran": "écran",
        "education": "éducation",
        "effet": "effet",
        "effort": "effort",
        "egalement": "également",
        "eglise": "église",
        "election": "élection",
        "element": "élément",
        "eleve": "élève",
        "elever": "élever",
        "eliminer": "éliminer",
        "elle": "elle",
        "email": "e-mail",
        "emission": "émission",
        "emotion": "émotion",
        "emploi": "emploi",
        "employer": "employer",
        "emporter": "emporter",
        "energie": "énergie",
        "enfant": "enfant",
        "enigme": "énigme",
        "ennemi": "ennemi",
        "enorme": "énorme",
        "enormement": "énormément",
        "enquete": "enquête",
        "ensemble": "ensemble",
        "ensuite": "ensuite",
        "entendre": "entendre",
        "entier": "entier",
        "entiere": "entière",
        "entierement": "entièrement",
        "entre": "entre",
        "entree": "entrée",
        "entreprise": "entreprise",
        "entrer": "entrer",
        "environnement": "environnement",
        "envoyer": "envoyer",
        "epoque": "époque",
        "equipe": "équipe",
        "erreur": "erreur",
        "escalier": "escalier",
        "espace": "espace",
        "espece": "espèce",
        "esperer": "espérer",
        "espere": "espère",
        "espoir": "espoir",
        "esprit": "esprit",
        "essayer": "essayer",
        "essentiel": "essentiel",
        "essentielle": "essentielle",
        "etablir": "établir",
        "etablissement": "établissement",
        "etage": "étage",
        "etape": "étape",
        "etat": "état",
        "etats-unis": "États-Unis",
        "etoile": "étoile",
        "etonnant": "étonnant",
        "etonner": "étonner",
        "etrange": "étrange",
        "etrangement": "étrangement",
        "etranger": "étranger",
        "etrangere": "étrangère",
        "etroit": "étroit",
        "etude": "étude",
        "etudiant": "étudiant",
        "etudiante": "étudiante",
        "etudier": "étudier",
        "evenement": "événement",
        "evenements": "événements",
        "eventuel": "éventuel",
        "eventuellement": "éventuellement",
        "evidemment": "évidemment",
        "evidence": "évidence",
        "evident": "évident",
        "eviter": "éviter",
        "evolution": "évolution",
        "exact": "exact",
        "exactement": "exactement",

        // café, idée, musée, etc.
        "cafe": "café",
        "the": "thé",
        "idee": "idée",
        "musee": "musée",
        "annee": "année",
        "journee": "journée",
        "soiree": "soirée",
        "matinee": "matinée",
        "arrivee": "arrivée",
        "sortie": "sortie",
        "cle": "clé",
        "cote": "côté",
        "sante": "santé",
        "beaute": "beauté",
        "societe": "société",
        "realite": "réalité",
        "qualite": "qualité",
        "quantite": "quantité",
        "securite": "sécurité",
        "liberte": "liberté",
        "egalite": "égalité",
        "fraternite": "fraternité",
        "verite": "vérité",
        "difficulte": "difficulté",
        "possibilite": "possibilité",
        "responsabilite": "responsabilité",
        "activite": "activité",
        "universite": "université",
        "nationalite": "nationalité",
        "personnalite": "personnalité",
        "electricite": "électricité",
        "publicite": "publicité",
        "majorite": "majorité",
        "priorite": "priorité",
        "capacite": "capacité",
        "identite": "identité",
        "autorite": "autorité",
        "communaute": "communauté",
        "creativite": "créativité",
        "curiosite": "curiosité",
        "diversite": "diversité",
        "efficacite": "efficacité",
        "facilite": "facilité",
        "fidelite": "fidélité",
        "flexibilite": "flexibilité",
        "humanite": "humanité",
        "legalite": "légalité",
        "mentalite": "mentalité",
        "mobilite": "mobilité",
        "moralite": "moralité",
        "necessite": "nécessité",
        "nouveaute": "nouveauté",
        "opportunite": "opportunité",
        "originalite": "originalité",
        "pauvrete": "pauvreté",
        "popularite": "popularité",
        "probabilite": "probabilité",
        "productivite": "productivité",
        "propriete": "propriété",
        "proximite": "proximité",
        "purete": "pureté",
        "rapidite": "rapidité",
        "rarete": "rareté",
        "regularite": "régularité",
        "sensibilite": "sensibilité",
        "serenite": "sérénité",
        "severite": "sévérité",
        "simplicite": "simplicité",
        "sincerite": "sincérité",
        "solidarite": "solidarité",
        "stabilite": "stabilité",
        "superiorite": "supériorité",
        "tranquillite": "tranquillité",
        "utilite": "utilité",
        "validite": "validité",
        "variete": "variété",
        "velocite": "vélocité",
        "volonte": "volonté",

        // Common words with è (grave accent)
        "pere": "père",
        "mere": "mère",
        "frere": "frère",
        "tres": "très",
        "apres": "après",
        "pres": "près",
        "aupres": "auprès",
        "succes": "succès",
        "acces": "accès",
        "proces": "procès",
        "progres": "progrès",
        "congres": "congrès",
        "expres": "exprès",
        "premiere": "première",
        "derniere": "dernière",
        "entiere": "entière",
        "particuliere": "particulière",
        "reguliere": "régulière",
        "maniere": "manière",
        "matiere": "matière",
        "lumiere": "lumière",
        "riviere": "rivière",
        "frontiere": "frontière",
        "carriere": "carrière",
        "priere": "prière",
        "poussiere": "poussière",
        "chere": "chère",
        "fiere": "fière",
        "colere": "colère",
        "misere": "misère",
        "sincere": "sincère",
        "atmosphere": "atmosphère",
        "caractere": "caractère",
        "mystere": "mystère",
        "critere": "critère",
        "modele": "modèle",
        "fidele": "fidèle",
        "parallele": "parallèle",
        "probleme": "problème",
        "systeme": "système",
        "theme": "thème",
        "poeme": "poème",
        "schema": "schéma",
        "phenomene": "phénomène",
        "strategie": "stratégie",
        "scene": "scène",
        "regle": "règle",
        "fleche": "flèche",
        "seche": "sèche",
        "levre": "lèvre",
        "fievre": "fièvre",
        "pievre": "pièvre",
        "creme": "crème",
        "legende": "légende",
        "piege": "piège",
        "siege": "siège",
        "college": "collège",
        "liege": "liège",
        "neige": "neige",
        "manege": "manège",
        "sorciere": "sorcière",
        "boulangere": "boulangère",
        "infirmiere": "infirmière",
        "ouvriere": "ouvrière",
        "cuisiniere": "cuisinière",
        "bergere": "bergère",
        "menagere": "ménagère",

        // Common words with ê (circumflex)
        "fete": "fête",
        "tete": "tête",
        "bete": "bête",
        "honnete": "honnête",
        "foret": "forêt",
        "interet": "intérêt",
        "fenetre": "fenêtre",
        "peut-etre": "peut-être",
        "meme": "même",
        "extreme": "extrême",
        "supreme": "suprême",
        "reve": "rêve",
        "rever": "rêver",
        "arret": "arrêt",
        "arreter": "arrêter",
        "pret": "prêt",
        "prete": "prête",
        "preter": "prêter",
        "enquete": "enquête",
        "requete": "requête",
        "conquete": "conquête",
        "tempete": "tempête",
        "aine": "aîné",
        "ainee": "aînée",
        "chaine": "chaîne",
        "trainer": "traîner",
        "naitre": "naître",
        "paraitre": "paraître",
        "connaitre": "connaître",
        "reconnaitre": "reconnaître",
        "disparaitre": "disparaître",
        "apparaitre": "apparaître",
        "maitre": "maître",
        "maitresse": "maîtresse",
        "maitrise": "maîtrise",
        "maitriser": "maîtriser",
        "fraiche": "fraîche",
        "fraicheur": "fraîcheur",
        "traitre": "traître",
        "croitre": "croître",
        "accroitre": "accroître",
        "decroitre": "décroître",
        "cloitre": "cloître",
        "epietre": "épitre",

        // Common words with à (grave accent)
        "la": "là",
        "ou": "où",
        "voila": "voilà",
        "deja": "déjà",
        "dela": "delà",

        // Common words with û (circumflex)
        "sur": "sûr",
        "mur": "mûr",
        "du": "dû",
        "dus": "dûs",
        "flute": "flûte",
        "buche": "bûche",
        "brulure": "brûlure",
        "bruler": "brûler",
        "cout": "coût",
        "gout": "goût",
        "gouter": "goûter",
        "aout": "août",
        "croute": "croûte",
        "voute": "voûte",

        // Common words with î (circumflex)
        "ile": "île",
        "diner": "dîner",
        "abime": "abîme",
        "boite": "boîte",
        "epitre": "épître",
        "huitre": "huître",
        "traitre": "traître",

        // Common words with ô (circumflex)
        "hotel": "hôtel",
        "hopital": "hôpital",
        "role": "rôle",
        "controle": "contrôle",
        "controler": "contrôler",
        "pole": "pôle",
        "diplome": "diplôme",
        "fantome": "fantôme",
        "symptome": "symptôme",
        "tot": "tôt",
        "plutot": "plutôt",
        "aussitot": "aussitôt",
        "bientot": "bientôt",
        "sitot": "sitôt",
        "tantot": "tantôt",
        "notre": "nôtre",
        "votre": "vôtre",
        "cloture": "clôture",
        "depot": "dépôt",
        "entrepot": "entrepôt",
        "impot": "impôt",
        "prevot": "prévôt",
        "aromes": "arômes",

        // Common words with ç (cedilla)
        "francais": "français",
        "francaise": "française",
        "garcon": "garçon",
        "lecon": "leçon",
        "facon": "façon",
        "recois": "reçois",
        "recoit": "reçoit",
        "recoivent": "reçoivent",
        "recu": "reçu",
        "apercu": "aperçu",
        "decu": "déçu",
        "concu": "conçu",
        "faconne": "façonné",
        "commencais": "commençais",
        "commencait": "commençait",
        "commencaient": "commençaient",
        "commencant": "commençant",
        "commenca": "commença",
        "avancais": "avançais",
        "avancait": "avançait",
        "avanca": "avança",
        "lancais": "lançais",
        "lancait": "lançait",
        "lanca": "lança",
        "placais": "plaçais",
        "placait": "plaçait",
        "placa": "plaça",
        "remplacais": "remplaçais",
        "remplacait": "remplaçait",
        "remplaca": "remplaça",
        "effacais": "effaçais",
        "effacait": "effaçait",
        "effaca": "effaça",
        "menacais": "menaçais",
        "menacait": "menaçait",
        "menaca": "menaça",
        "annoncais": "annonçais",
        "annoncait": "annonçait",
        "annonca": "annonça",
        "prononcais": "prononçais",
        "prononcait": "prononçait",
        "prononca": "prononça",
        "exercais": "exerçais",
        "exercait": "exerçait",
        "exerca": "exerça",
        "financais": "finançais",
        "financait": "finançait",
        "financa": "finança",
        "influencais": "influençais",
        "influencait": "influençait",
        "influenca": "influença",
        "sucon": "suçon",
        "hamecon": "hameçon",
        "macon": "maçon",
        "soupcon": "soupçon",
        "rancon": "rançon",
        "glacon": "glaçon",
        "limacon": "limaçon",
        "poincon": "poinçon",
        "troncon": "tronçon",
        "facade": "façade",
        "fiancailles": "fiançailles",
        "fiance": "fiancé",
        "fiancee": "fiancée",
        "balancoire": "balançoire",
        "percoir": "perçoir",

        // Common words with ë (diaeresis)
        "noel": "Noël",

        // Common words with ï (diaeresis)
        "mais": "maïs",
        "naive": "naïve",
        "naif": "naïf",
        "egoiste": "égoïste",
        "heroique": "héroïque",
        "archaique": "archaïque",
        "mosaique": "mosaïque",
        "laique": "laïque",
        "coincidence": "coïncidence",
        "coincider": "coïncider",

        // ==========================================
        // COMMON VERBS WITH ACCENTS
        // ==========================================

        // -er verbs with accents
        "preferer": "préférer",
        "prefere": "préfère",
        "preferes": "préfères",
        "repeter": "répéter",
        "repete": "répète",
        "repetes": "répètes",
        "esperer": "espérer",
        "espere": "espère",
        "esperes": "espères",
        "considerer": "considérer",
        "considere": "considère",
        "consideres": "considères",
        "posseder": "posséder",
        "possede": "possède",
        "possedes": "possèdes",
        "celebrer": "célébrer",
        "celebre": "célèbre",
        "celebres": "célèbres",
        "tolerer": "tolérer",
        "tolere": "tolère",
        "toleres": "tolères",
        "exagerer": "exagérer",
        "exagere": "exagère",
        "exageres": "exagères",
        "gerer": "gérer",
        "gere": "gère",
        "geres": "gères",
        "suggerer": "suggérer",
        "suggere": "suggère",
        "suggeres": "suggères",
        "accelerer": "accélérer",
        "accelere": "accélère",
        "acceleres": "accélères",
        "reveler": "révéler",
        "revele": "révèle",
        "reveles": "révèles",
        "interpreter": "interpréter",
        "interprete": "interprète",
        "interpretes": "interprètes",
        "completer": "compléter",
        "complete": "complète",
        "completes": "complètes",
        "inquieter": "inquiéter",
        "inquiete": "inquiète",
        "inquietes": "inquiètes",
        "penetrer": "pénétrer",
        "penetre": "pénètre",
        "penetres": "pénètres",
        "liberer": "libérer",
        "libere": "libère",
        "liberes": "libères",
        "moderer": "modérer",
        "modere": "modère",
        "moderes": "modères",
        "operer": "opérer",
        "opere": "opère",
        "operes": "opères",
        "recuperer": "récupérer",
        "recupere": "récupère",
        "recuperes": "récupères",
        "digerer": "digérer",
        "digere": "digère",
        "digeres": "digères",
        "referer": "référer",
        "refere": "réfère",
        "referes": "réfères",
        "differer": "différer",
        "differe": "diffère",
        "differes": "diffères",
        "transferer": "transférer",
        "transfere": "transfère",
        "transferes": "transfères",
        "interferer": "interférer",
        "interfere": "interfère",
        "interferes": "interfères",
        "conferer": "conférer",
        "confere": "confère",
        "conferes": "confères",
        "inserer": "insérer",
        "insere": "insère",
        "inseres": "insères",
        "alterer": "altérer",
        "altere": "altère",
        "alteres": "altères",
        "generer": "générer",
        "genere": "génère",
        "generes": "génères",
        "enumerer": "énumérer",
        "enumere": "énumère",
        "enumeres": "énumères",
        "remunerer": "rémunérer",
        "remunere": "rémunère",
        "remuneres": "rémunères",
        "venerer": "vénérer",
        "venere": "vénère",
        "veneres": "vénères",
        "prosperer": "prospérer",
        "prospere": "prospère",
        "prosperes": "prospères",
        "cooperer": "coopérer",
        "coopere": "coopère",
        "cooperes": "coopères",
        "federer": "fédérer",
        "federe": "fédère",
        "federes": "fédères",
        "temperer": "tempérer",
        "tempere": "tempère",
        "temperes": "tempères",

        // -ir verbs with accents
        "reussir": "réussir",
        "reussis": "réussis",
        "reussit": "réussit",
        "reunir": "réunir",
        "reunis": "réunis",
        "reunit": "réunit",
        "reflechir": "réfléchir",
        "reflechis": "réfléchis",
        "reflechit": "réfléchit",

        // -re verbs with accents
        "resoudre": "résoudre",
        "resous": "résous",
        "resout": "résout",

        // ==========================================
        // COMMON ADJECTIVES WITH ACCENTS
        // ==========================================

        "general": "général",
        "generale": "générale",
        "generaux": "généraux",
        "special": "spécial",
        "speciale": "spéciale",
        "speciaux": "spéciaux",
        "different": "différent",
        "differente": "différente",
        "differents": "différents",
        "necessaire": "nécessaire",
        "necessaires": "nécessaires",
        "particulier": "particulier",
        "particuliere": "particulière",
        "regulier": "régulier",
        "reguliere": "régulière",
        "superieur": "supérieur",
        "superieure": "supérieure",
        "inferieur": "inférieur",
        "inferieure": "inférieure",
        "anterieur": "antérieur",
        "anterieure": "antérieure",
        "posterieur": "postérieur",
        "posterieure": "postérieure",
        "exterieur": "extérieur",
        "exterieure": "extérieure",
        "interieur": "intérieur",
        "interieure": "intérieure",
        "leger": "léger",
        "legere": "légère",
        "severe": "sévère",
        "celebre": "célèbre",
        "seche": "sèche",
        "grec": "grec",
        "grecque": "grecque",
        "turc": "turc",
        "turque": "turque",
        "public": "public",
        "publique": "publique",
        "poetique": "poétique",
        "esthetique": "esthétique",
        "ethique": "éthique",
        "economique": "économique",
        "electrique": "électrique",
        "electronique": "électronique",
        "energetique": "énergétique",
        "genetique": "génétique",
        "theorique": "théorique",
        "specifique": "spécifique",
        "scientifique": "scientifique",
        "magnifique": "magnifique",
        "fantastique": "fantastique",
        "romantique": "romantique",
        "dramatique": "dramatique",
        "automatique": "automatique",
        "systematique": "systématique",
        "democratique": "démocratique",
        "diplomatique": "diplomatique",
        "authentique": "authentique",
        "sympathique": "sympathique",
        "pathetique": "pathétique",
        "prefere": "préféré",
        "preferee": "préférée",
        "interesse": "intéressé",
        "interessant": "intéressant",

        // ==========================================
        // COMMON ADVERBS WITH ACCENTS
        // ==========================================

        "generalement": "généralement",
        "specialement": "spécialement",
        "particulierement": "particulièrement",
        "regulierement": "régulièrement",
        "completement": "complètement",
        "sincerement": "sincèrement",
        "severement": "sévèrement",
        "legerement": "légèrement",
        "entierement": "entièrement",
        "immediatement": "immédiatement",
        "definitivement": "définitivement",
        "evidemment": "évidemment",
        "reellement": "réellement",
        "veritablement": "véritablement",
        "enormement": "énormément",
        "etrangement": "étrangement",
        "secretement": "secrètement",
        "discretement": "discrètement",
        "concretement": "concrètement",
        "precisement": "précisément",
        "separement": "séparément",
        "moderement": "modérément",
        "delicatement": "délicatement",
        "deliberement": "délibérément",
        "desesperement": "désespérément",

        // ==========================================
        // COMMON NOUNS WITH ACCENTS
        // ==========================================

        // Time-related
        "siecle": "siècle",
        "periode": "période",
        "ere": "ère",
        "fevrier": "février",
        "decembre": "décembre",

        // Places and locations
        "region": "région",
        "departement": "département",
        "prefecture": "préfecture",
        "theatre": "théâtre",
        "cinema": "cinéma",
        "opera": "opéra",
        "bibliotheque": "bibliothèque",
        "cathedrale": "cathédrale",
        "chateau": "château",

        // People and professions
        "president": "président",
        "secretaire": "secrétaire",
        "medecin": "médecin",
        "ingenieur": "ingénieur",
        "ecrivain": "écrivain",
        "delegue": "délégué",
        "depute": "député",
        "refugie": "réfugié",
        "celebrite": "célébrité",

        // Abstract nouns
        "methode": "méthode",
        "theorie": "théorie",
        "categorie": "catégorie",
        "hierarchie": "hiérarchie",
        "democratie": "démocratie",
        "philosophie": "philosophie",
        "psychologie": "psychologie",
        "technologie": "technologie",
        "biologie": "biologie",
        "geographie": "géographie",
        "geometrie": "géométrie",
        "memoire": "mémoire",
        "ceremonie": "cérémonie",
        "experience": "expérience",
        "reference": "référence",
        "preference": "préférence",
        "difference": "différence",
        "conference": "conférence",
        "presence": "présence",
        "consequence": "conséquence",
        "frequence": "fréquence",
        "sequence": "séquence",
        "competence": "compétence",
        "resistance": "résistance",
        "independance": "indépendance",
        "dependance": "dépendance",
        "tolerance": "tolérance",
        "elegance": "élégance",
        "reponse": "réponse",
        "numero": "numéro",
        "telephone": "téléphone",

        // ==========================================
        // COMMON EXPRESSIONS AND PHRASES
        // ==========================================

        "a bientot": "à bientôt",
        "a demain": "à demain",
        "a plus tard": "à plus tard",
        "a cote": "à côté",
        "a peu pres": "à peu près",
        "la-bas": "là-bas",
        "tot ou tard": "tôt ou tard",
        "des": "dès",
        "des que": "dès que",

        // Ordinal numbers
        "deuxieme": "deuxième",
        "troisieme": "troisième",
        "quatrieme": "quatrième",
        "cinquieme": "cinquième",
        "sixieme": "sixième",
        "septieme": "septième",
        "huitieme": "huitième",
        "neuvieme": "neuvième",
        "dixieme": "dixième",
        "onzieme": "onzième",
        "douzieme": "douzième",
        "treizieme": "treizième",
        "quatorzieme": "quatorzième",
        "quinzieme": "quinzième",
        "seizieme": "seizième",
        "dix-septieme": "dix-septième",
        "dix-huitieme": "dix-huitième",
        "dix-neuvieme": "dix-neuvième",
        "vingtieme": "vingtième",
        "centieme": "centième",
        "millieme": "millième",
    ]

    // MARK: - French Misspellings Dictionary
    // Common spelling mistakes in French

    private static let frenchMisspellings: [String: String] = [
        // Double consonant errors
        "language": "langage",
        "apartement": "appartement",
        "appartment": "appartement",
        "appercevoir": "apercevoir",
        "appellé": "appelé",
        "appeller": "appeler",
        "attent": "attend",
        "ballance": "balance",
        "ballancer": "balancer",
        "benefice": "bénéfice",
        "bizzare": "bizarre",
        "charactere": "caractère",
        "comission": "commission",
        "connection": "connexion",
        "developper": "développer",
        "developpement": "développement",
        "differance": "différence",
        "differant": "différent",
        "disussion": "discussion",
        "environment": "environnement",
        "environement": "environnement",
        "excellant": "excellent",
        "excercice": "exercice",
        "exellent": "excellent",
        "exsemple": "exemple",
        "famillier": "familier",
        "gobernment": "gouvernement",
        "gouvernament": "gouvernement",
        "grammer": "grammaire",
        "guaranti": "garanti",
        "independant": "indépendant",
        "inteligence": "intelligence",
        "litterature": "littérature",
        "maintainance": "maintenance",
        "maintenence": "maintenance",
        "millieu": "milieu",
        "milion": "million",
        "millionare": "millionnaire",
        "neccessaire": "nécessaire",
        "ocassion": "occasion",
        "ocasion": "occasion",
        "occassion": "occasion",
        "occurence": "occurrence",
        "oportunite": "opportunité",
        "paralelle": "parallèle",
        "parralele": "parallèle",
        "parmis": "parmi",
        "personel": "personnel",
        "personnal": "personnel",
        "possesion": "possession",
        "profesional": "professionnel",
        "professionel": "professionnel",
        "programm": "programme",
        "proggrame": "programme",
        "recomandation": "recommandation",
        "recomender": "recommander",
        "recommendar": "recommander",
        "resistence": "résistance",
        "silance": "silence",
        "success": "succès",
        "suffisament": "suffisamment",
        "surprize": "surprise",
        "tecnique": "technique",
        "tendence": "tendance",
        "traditionel": "traditionnel",
        "traditionnal": "traditionnel",
        "transforer": "transférer",

        // Common letter substitution errors
        "accomodation": "accommodation",
        "accomodder": "accommoder",
        "aquérir": "acquérir",
        "definitvement": "définitivement",
        "definitivment": "définitivement",
        "exellence": "excellence",
        "maintenent": "maintenant",
        "naturelment": "naturellement",
        "normallement": "normalement",
        "normalment": "normalement",

        // Silent letter errors
        "temp": "temps",
        "corp": "corps",
        "doit": "doigt",

        // Common anglicisms to correct
        "checker": "vérifier",
        "weekend": "week-end",
        "brainstorming": "remue-méninges",
    ]

    // MARK: - French Proper Nouns
    // Cities, regions, countries, and other proper nouns requiring capitalization

    private static let frenchProperNouns: [String: String] = [
        // ==========================================
        // MAJOR FRENCH CITIES
        // ==========================================

        "paris": "Paris",
        "marseille": "Marseille",
        "lyon": "Lyon",
        "toulouse": "Toulouse",
        "nice": "Nice",
        "nantes": "Nantes",
        "montpellier": "Montpellier",
        "strasbourg": "Strasbourg",
        "bordeaux": "Bordeaux",
        "lille": "Lille",
        "rennes": "Rennes",
        "reims": "Reims",
        "saint-etienne": "Saint-Étienne",
        "le havre": "Le Havre",
        "toulon": "Toulon",
        "grenoble": "Grenoble",
        "dijon": "Dijon",
        "angers": "Angers",
        "nimes": "Nîmes",
        "villeurbanne": "Villeurbanne",
        "aix-en-provence": "Aix-en-Provence",
        "clermont-ferrand": "Clermont-Ferrand",
        "le mans": "Le Mans",
        "brest": "Brest",
        "tours": "Tours",
        "amiens": "Amiens",
        "limoges": "Limoges",
        "annecy": "Annecy",
        "perpignan": "Perpignan",
        "besancon": "Besançon",
        "orleans": "Orléans",
        "metz": "Metz",
        "rouen": "Rouen",
        "mulhouse": "Mulhouse",
        "caen": "Caen",
        "nancy": "Nancy",
        "argenteuil": "Argenteuil",
        "saint-denis": "Saint-Denis",
        "roubaix": "Roubaix",
        "tourcoing": "Tourcoing",
        "montreuil": "Montreuil",
        "avignon": "Avignon",
        "dunkerque": "Dunkerque",
        "nanterre": "Nanterre",
        "creteil": "Créteil",
        "poitiers": "Poitiers",
        "versailles": "Versailles",
        "pau": "Pau",
        "la rochelle": "La Rochelle",
        "calais": "Calais",
        "antibes": "Antibes",
        "cannes": "Cannes",
        "saint-tropez": "Saint-Tropez",
        "biarritz": "Biarritz",
        "deauville": "Deauville",
        "honfleur": "Honfleur",
        "carcassonne": "Carcassonne",
        "saint-malo": "Saint-Malo",
        "ajaccio": "Ajaccio",
        "bastia": "Bastia",
        "lourdes": "Lourdes",
        "vichy": "Vichy",
        "megeve": "Megève",
        "chamonix": "Chamonix",
        "evian": "Évian",

        // ==========================================
        // FRENCH REGIONS
        // ==========================================

        "ile-de-france": "Île-de-France",
        "auvergne-rhone-alpes": "Auvergne-Rhône-Alpes",
        "nouvelle-aquitaine": "Nouvelle-Aquitaine",
        "occitanie": "Occitanie",
        "hauts-de-france": "Hauts-de-France",
        "provence-alpes-cote d'azur": "Provence-Alpes-Côte d'Azur",
        "grand est": "Grand Est",
        "pays de la loire": "Pays de la Loire",
        "bretagne": "Bretagne",
        "normandie": "Normandie",
        "bourgogne-franche-comte": "Bourgogne-Franche-Comté",
        "centre-val de loire": "Centre-Val de Loire",
        "corse": "Corse",
        "martinique": "Martinique",
        "guadeloupe": "Guadeloupe",
        "guyane": "Guyane",
        "la reunion": "La Réunion",
        "mayotte": "Mayotte",

        // Historical regions
        "alsace": "Alsace",
        "lorraine": "Lorraine",
        "champagne": "Champagne",
        "picardie": "Picardie",
        "bourgogne": "Bourgogne",
        "franche-comte": "Franche-Comté",
        "aquitaine": "Aquitaine",
        "midi-pyrenees": "Midi-Pyrénées",
        "languedoc-roussillon": "Languedoc-Roussillon",
        "rhone-alpes": "Rhône-Alpes",
        "poitou-charentes": "Poitou-Charentes",
        "limousin": "Limousin",
        "auvergne": "Auvergne",
        "provence": "Provence",
        "dauphine": "Dauphiné",
        "savoie": "Savoie",
        "cote d'azur": "Côte d'Azur",

        // ==========================================
        // EUROPEAN COUNTRIES
        // ==========================================

        "france": "France",
        "allemagne": "Allemagne",
        "angleterre": "Angleterre",
        "royaume-uni": "Royaume-Uni",
        "grande-bretagne": "Grande-Bretagne",
        "ecosse": "Écosse",
        "pays de galles": "Pays de Galles",
        "irlande": "Irlande",
        "italie": "Italie",
        "espagne": "Espagne",
        "portugal": "Portugal",
        "belgique": "Belgique",
        "pays-bas": "Pays-Bas",
        "hollande": "Hollande",
        "luxembourg": "Luxembourg",
        "suisse": "Suisse",
        "autriche": "Autriche",
        "pologne": "Pologne",
        "republique tcheque": "République tchèque",
        "slovaquie": "Slovaquie",
        "hongrie": "Hongrie",
        "roumanie": "Roumanie",
        "bulgarie": "Bulgarie",
        "grece": "Grèce",
        "turquie": "Turquie",
        "russie": "Russie",
        "ukraine": "Ukraine",
        "bielorussie": "Biélorussie",
        "lituanie": "Lituanie",
        "lettonie": "Lettonie",
        "estonie": "Estonie",
        "finlande": "Finlande",
        "suede": "Suède",
        "norvege": "Norvège",
        "danemark": "Danemark",
        "islande": "Islande",
        "croatie": "Croatie",
        "slovenie": "Slovénie",
        "serbie": "Serbie",
        "montenegro": "Monténégro",
        "bosnie-herzegovine": "Bosnie-Herzégovine",
        "macedoine": "Macédoine",
        "albanie": "Albanie",
        "moldavie": "Moldavie",
        "chypre": "Chypre",
        "malte": "Malte",
        "andorre": "Andorre",
        "monaco": "Monaco",

        // ==========================================
        // OTHER COUNTRIES
        // ==========================================

        // Americas
        "etats-unis": "États-Unis",
        "amerique": "Amérique",
        "canada": "Canada",
        "quebec": "Québec",
        "mexique": "Mexique",
        "bresil": "Brésil",
        "argentine": "Argentine",
        "chili": "Chili",
        "colombie": "Colombie",
        "perou": "Pérou",
        "venezuela": "Venezuela",
        "cuba": "Cuba",
        "haiti": "Haïti",

        // Africa
        "afrique": "Afrique",
        "maroc": "Maroc",
        "algerie": "Algérie",
        "tunisie": "Tunisie",
        "egypte": "Égypte",
        "senegal": "Sénégal",
        "cote d'ivoire": "Côte d'Ivoire",
        "cameroun": "Cameroun",
        "congo": "Congo",
        "afrique du sud": "Afrique du Sud",
        "madagascar": "Madagascar",

        // Asia
        "asie": "Asie",
        "chine": "Chine",
        "japon": "Japon",
        "coree": "Corée",
        "coree du sud": "Corée du Sud",
        "coree du nord": "Corée du Nord",
        "inde": "Inde",
        "pakistan": "Pakistan",
        "vietnam": "Vietnam",
        "thailande": "Thaïlande",
        "indonesie": "Indonésie",
        "malaisie": "Malaisie",
        "singapour": "Singapour",
        "philippines": "Philippines",
        "iran": "Iran",
        "irak": "Irak",
        "arabie saoudite": "Arabie saoudite",
        "emirats arabes unis": "Émirats arabes unis",
        "qatar": "Qatar",
        "israel": "Israël",
        "liban": "Liban",
        "syrie": "Syrie",
        "jordanie": "Jordanie",

        // Oceania
        "oceanie": "Océanie",
        "australie": "Australie",
        "nouvelle-zelande": "Nouvelle-Zélande",
        "polynesie": "Polynésie",
        "nouvelle-caledonie": "Nouvelle-Calédonie",

        // ==========================================
        // MAJOR CITIES WORLDWIDE
        // ==========================================

        "londres": "Londres",
        "berlin": "Berlin",
        "madrid": "Madrid",
        "rome": "Rome",
        "amsterdam": "Amsterdam",
        "bruxelles": "Bruxelles",
        "vienne": "Vienne",
        "munich": "Munich",
        "francfort": "Francfort",
        "barcelone": "Barcelone",
        "lisbonne": "Lisbonne",
        "athenes": "Athènes",
        "moscou": "Moscou",
        "saint-petersbourg": "Saint-Pétersbourg",
        "varsovie": "Varsovie",
        "budapest": "Budapest",
        "prague": "Prague",
        "stockholm": "Stockholm",
        "oslo": "Oslo",
        "copenhague": "Copenhague",
        "helsinki": "Helsinki",
        "dublin": "Dublin",
        "edimbourg": "Édimbourg",
        "zurich": "Zurich",
        "geneve": "Genève",
        "new york": "New York",
        "los angeles": "Los Angeles",
        "washington": "Washington",
        "chicago": "Chicago",
        "san francisco": "San Francisco",
        "miami": "Miami",
        "boston": "Boston",
        "montreal": "Montréal",
        "toronto": "Toronto",
        "vancouver": "Vancouver",
        "mexico": "Mexico",
        "rio de janeiro": "Rio de Janeiro",
        "sao paulo": "São Paulo",
        "buenos aires": "Buenos Aires",
        "pekin": "Pékin",
        "shanghai": "Shanghai",
        "tokyo": "Tokyo",
        "seoul": "Séoul",
        "delhi": "Delhi",
        "mumbai": "Mumbai",
        "bangkok": "Bangkok",
        "hong kong": "Hong Kong",
        "sydney": "Sydney",
        "melbourne": "Melbourne",
        "le caire": "Le Caire",
        "casablanca": "Casablanca",
        "dakar": "Dakar",
        "dubai": "Dubaï",
        "tel-aviv": "Tel-Aviv",
        "jerusalem": "Jérusalem",
        "istanbul": "Istanbul",

        // ==========================================
        // FRENCH GEOGRAPHY
        // ==========================================

        // Rivers
        "seine": "Seine",
        "loire": "Loire",
        "garonne": "Garonne",
        "rhone": "Rhône",
        "rhin": "Rhin",
        "meuse": "Meuse",
        "moselle": "Moselle",
        "dordogne": "Dordogne",
        "charente": "Charente",
        "somme": "Somme",
        "marne": "Marne",
        "oise": "Oise",
        "yonne": "Yonne",
        "saone": "Saône",
        "isere": "Isère",
        "durance": "Durance",
        "tarn": "Tarn",
        "lot": "Lot",
        "adour": "Adour",

        // Mountains
        "alpes": "Alpes",
        "pyrenees": "Pyrénées",
        "massif central": "Massif central",
        "vosges": "Vosges",
        "jura": "Jura",
        "mont blanc": "Mont Blanc",
        "mont-blanc": "Mont-Blanc",

        // Seas and oceans
        "mediterranee": "Méditerranée",
        "atlantique": "Atlantique",
        "manche": "Manche",
        "mer du nord": "Mer du Nord",

        // Famous landmarks
        "tour eiffel": "Tour Eiffel",
        "arc de triomphe": "Arc de Triomphe",
        "notre-dame": "Notre-Dame",
        "sacre-coeur": "Sacré-Coeur",
        "louvre": "Louvre",
        "mont-saint-michel": "Mont-Saint-Michel",
        "champs-elysees": "Champs-Élysées",
        "montmartre": "Montmartre",
        "saint-germain-des-pres": "Saint-Germain-des-Prés",
        "quartier latin": "Quartier latin",
        "tuileries": "Tuileries",
        "invalides": "Invalides",
        "pantheon": "Panthéon",
        "bastille": "Bastille",
        "concorde": "Concorde",
        "la defense": "La Défense",
    ]

    // MARK: - French Abbreviations

    /// Common French abbreviations
    static let frenchAbbreviations: Set<String> = [
        // Titles
        "M.", "Mme", "Mlle", "Dr", "Pr", "Me",

        // Common abbreviations
        "etc.", "ex.", "cf.", "c.-à-d.", "c'est-à-dire",
        "p. ex.", "N.B.", "P.-S.", "env.", "approx.",
        "min.", "max.", "inc.", "déc.",

        // Measurements
        "kg", "g", "mg", "km", "m", "cm", "mm",
        "l", "ml", "cl", "dl",
        "h", "min", "s", "sec",
        "°C", "°F",

        // Address
        "av.", "bd", "pl.", "r.", "rue",
        "n°", "apt.", "appt.",

        // Time
        "av. J.-C.", "apr. J.-C.",
        "janv.", "févr.", "mars", "avr.", "mai", "juin",
        "juil.", "août", "sept.", "oct.", "nov.", "déc.",
        "lun.", "mar.", "mer.", "jeu.", "ven.", "sam.", "dim.",

        // Currency
        "€", "EUR", "CHF", "$", "USD", "CAD",

        // Business
        "S.A.", "S.A.R.L.", "SAS", "SARL",
        "SA", "Cie", "Sté",
        "PDG", "DG", "DRH",

        // Organizations
        "ONU", "UE", "OTAN", "OMS",
        "SNCF", "RATP", "EDF", "GDF",

        // Common French-specific
        "qqn", "qqch", "qd", "qq.", "bcp",
        "stp", "svp", "rdv", "pb",
        "tjrs", "tjs", "càd",
    ]
}
